apiVersion: apps/v1
kind: Deployment
metadata:
  name: plumber-fe
  namespace: {{ .Values.namespace }}
  labels:
    app: plumber-fe
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: plumber-fe
  template:
    metadata:
      labels:
        app: plumber-fe
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.targetPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.targetPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
---
apiVersion: v1
kind: Service
metadata:
  name: plumber-fe
  namespace: {{ .Values.namespace }}
  labels:
    app: plumber-fe
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.servicePort }}
      targetPort: {{ .Values.frontend.targetPort }}
  selector:
    app: plumber-fe
