{{- if and .Values.serviceAccount.create .Values.serviceAccount.name }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
{{- end }}
